### ISSUE TITLE
Enable a "dev" mode to generate docs for all dependencies like in rust

### ISSUE THREAD

**Issue by mpadge** [ropenscilabs/r2readthedocs#8]
RTD would be an ideal system to enable generation of "dev mode" documentation like in rust, where the `.Rd` databases of all (installed) dependencies are extracted and converted to items in a single, locally-generated site. That would be one unique and convincing demonstration of what this package can offer beyond more conventional, package-based documentation systems in R.

**Comment by mpadge** [comment]
PR #10 adds the base functionality.

## TODO

- [ ] ~~Parse `.Rd` `\concept` tags to group functions~~ Also not really possible within the structure of `.rst` tocs, so not worth doing (at the moment)
- [x] Create full package documentation, including landing page from `DESCRIPTION` file, and vignettes
- [x] Clean output of `Rd2md::Rd2markdown()` to remove all automatically-inserted hyperlinks, which are interpreted as local MyST link targets and trigger warnings from sphinx
- [ ] ~~Add title string for each function to package index page~~ - looks terrible, and puts full strings in toc panel, so a no-go
